name: universal_car_plates
description: >-
  A reusable Flutter widget that displays a car license plates , especially tunisians one 
  with correct layout, Arabic font, and customizable numbers.

version: 1.0.0
homepage: https://github.com/malekrmadi/universal_car_plate_package_pubdev 
repository: https://github.com/malekrmadi/universal_car_plate_package_pubdev 
issue_tracker: https://github.com/malekrmadi/universal_car_plate_package_pubdev 

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

  assets:
    - assets/fonts/
