name: universal_car_plates
description: >-
  A reusable Flutter widget that displays a Tunisian license plate
  with correct layout, Arabic font, and customizable numbers.

version: 0.0.1
homepage: https://github.com/malekrmadi/universal_car_plate_package_pubdev
repository: https://github.com/malekrmadi/universal_car_plate_package_pubdev
issue_tracker: https://github.com/malekrmadi/universal_car_plate_package_pubdev/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

  assets:
    - assets/fonts/
